function outputAngles = joint_motor_to_output_angles(motorAngles, transmission)
%JOINT_MOTOR_TO_OUTPUT_ANGLES Apply calibrated chain signs and zero offsets.

arguments
    motorAngles (2, 1) double {mustBeFinite}
    transmission (1, 1) struct
end

if ~transmission.isCalibrated || ...
        any(~isfinite(transmission.rotationSign)) || ...
        any(~isfinite(transmission.motorZeroRad)) || ...
        any(~isfinite(transmission.outputZeroRad))
    error('sixdof:Actuator:CalibrationRequired', ...
        '关节链传动符号与零位尚未标定。');
end
if any(abs(transmission.rotationSign) ~= 1)
    error('sixdof:Actuator:InvalidRotationSign', ...
        '每个链传动旋转符号必须为+1或-1。');
end
outputAngles = transmission.outputZeroRad + ...
    transmission.rotationSign .* ...
    transmission.outputPerMotorMagnitude .* ...
    (motorAngles - transmission.motorZeroRad);
end
