function actuators = serial_leg_actuator_parameters()
%SERIAL_LEG_ACTUATOR_PARAMETERS Combine manuals with verified CAD evidence.

cad = load_cad_serial_leg_geometry();
jointMotor = dm_j8009_parameters();
wheelMotor = m3508_c620_parameters();
sprockets = cad.sprocketGeometryEvidence;
if sprockets.common_estimated_tooth_count ~= 20 || ...
        sprockets.active_to_driven_speed_ratio_magnitude ~= 1
    error('sixdof:Actuator:UnexpectedSprocketEvidence', ...
        'CAD链轮齿形不再满足当前20齿、1:1幅值合同。');
end

actuators.jointMotor = jointMotor;
actuators.wheelMotor = wheelMotor;
actuators.jointTransmission.activeTeeth = [20; 20];
actuators.jointTransmission.drivenTeeth = [20; 20];
actuators.jointTransmission.outputPerMotorMagnitude = [1; 1];
actuators.jointTransmission.rotationSign = [NaN; NaN];
actuators.jointTransmission.motorZeroRad = [NaN; NaN];
actuators.jointTransmission.outputZeroRad = [NaN; NaN];
actuators.jointTransmission.efficiency = [NaN; NaN];
actuators.jointTransmission.isCalibrated = false;
actuators.jointTransmission.warning = ...
    "CAD确认四个链轮均约20齿；旋转符号、零位和效率仍需标定";
actuators.jointOutputRatedTorqueMagnitudeNm = ...
    jointMotor.ratedOutputTorqueNm * ones(2, 1);
actuators.jointOutputPeakTorqueMagnitudeNm = ...
    jointMotor.peakOutputTorqueNm * ones(2, 1);
actuators.wheelTransmission.stockM3508ReductionRatio = ...
    wheelMotor.internalReductionRatio;
% M3508 的 P19 输出之后，还要经过 CAD 轮边复合行星机构。
% STEP 只能给出齿数和装配关系，暂时不能证明固定件/输出件。
Ns = 17;
Np1 = 40;
Np2 = 10;
Nr = 67;
kCompound = -(Ns * Np2) / (Nr * Np1);
carrierFixedRatio = 1 / abs(kCompound);          % 齿圈输出候选
ringFixedRatio = 1 / abs(kCompound / (kCompound - 1)); % 保持架输出候选
actuators.wheelTransmission.cadPlanetaryTeeth = ...
    struct('sun', Ns, 'planetLarge', Np1, 'planetSmall', Np2, 'ring', Nr);
actuators.wheelTransmission.cadExternalRatioMagnitudeCandidates = ...
    [carrierFixedRatio; ringFixedRatio];
actuators.wheelTransmission.cadExternalRatioMagnitudeCandidate = ...
    carrierFixedRatio;
actuators.wheelTransmission.selectedTopology = ...
    "保持架固定、齿圈输出";
actuators.wheelTransmission.selectedExternalRatio = -carrierFixedRatio;
actuators.wheelTransmission.selectedExternalRatioMagnitude = carrierFixedRatio;
actuators.wheelTransmission.selectedExternalEfficiency = NaN;
actuators.wheelTransmission.selectedForSixDofSimulation = true;
actuators.wheelTransmission.cascadedRatioMagnitudeCandidate = ...
    wheelMotor.internalReductionRatio * ...
    actuators.wheelTransmission.cadExternalRatioMagnitudeCandidate;
actuators.wheelTransmission.cascadedRatioMagnitudeCandidates = ...
    wheelMotor.internalReductionRatio * ...
    actuators.wheelTransmission.cadExternalRatioMagnitudeCandidates;
actuators.wheelTransmission.ratedWheelSpeedRpmCandidate = ...
    wheelMotor.ratedOutputSpeedRpm / ...
    actuators.wheelTransmission.cadExternalRatioMagnitudeCandidate;
actuators.wheelTransmission.continuousWheelTorqueIdealNmCandidate = ...
    wheelMotor.ratedOutputTorqueNm * ...
    actuators.wheelTransmission.cadExternalRatioMagnitudeCandidate;
actuators.wheelTransmission.peakWheelTorqueIdealNmCandidate = ...
    wheelMotor.stallOutputTorqueNm * ...
    actuators.wheelTransmission.cadExternalRatioMagnitudeCandidate;
% 方向仅表示“太阳轮正转 -> 齿圈反向”，电机/轮编码器相对机器人坐标的
% 正方向仍需标定，因此这里不把它当作整机最终符号。
actuators.wheelTransmission.externalGearRatio = ...
    actuators.wheelTransmission.selectedExternalRatio;
actuators.wheelTransmission.totalMotorToWheelRatio = ...
    -wheelMotor.internalReductionRatio * ...
    actuators.wheelTransmission.selectedExternalRatioMagnitude;
actuators.wheelTransmission.isResolved = false;
actuators.wheelTransmission.warning = ...
    "六维暂按保持架固定、齿圈输出使用；效率、编码器方向和零位仍需实测确认";
end
