function result = validate_calibration_record_6dof(record)
%VALIDATE_CALIBRATION_RECORD_6DOF Check whether measured calibration is usable.

arguments
    record (1, 1) struct
end

requiredTopLevel = ["version", "timestamp", "operator", "firmwareCommit", ...
    "batteryVoltageV", "joint", "imu", "wheel"];
result.schemaComplete = all(isfield(record, requiredTopLevel));
if ~result.schemaComplete
    result.jointPass = false;
    result.imuPass = false;
    result.wheelPass = false;
    result.ready = false;
    result.blockers = "标定记录缺少必要字段";
    return;
end

result.metadataComplete = strlength(record.timestamp) > 0 && ...
    strlength(record.operator) > 0 && ...
    strlength(record.firmwareCommit) > 0 && ...
    isfinite(record.batteryVoltageV) && record.batteryVoltageV > 0;
result.jointPass = record.joint.isCalibrated && ...
    isequal(size(record.joint.rotationSign), [2, 1]) && ...
    all(abs(record.joint.rotationSign) == 1) && ...
    all(isfinite(record.joint.motorZeroRad)) && ...
    all(isfinite(record.joint.outputZeroRad)) && ...
    all(abs(record.joint.outputErrorRad) <= deg2rad(1));
result.imuPass = record.imu.isCalibrated && ...
    all(abs([record.imu.rightPitchSign, record.imu.leftPitchSign, ...
        record.imu.rightGyroYSign, record.imu.leftGyroYSign]) == 1) && ...
    isfinite(record.imu.staticGyroRmsRadPerS) && ...
    record.imu.staticGyroRmsRadPerS < 0.02;
result.wheelPass = record.wheel.isResolved && ...
    isfinite(record.wheel.motorToWheelRatioMagnitude) && ...
    record.wheel.motorToWheelRatioMagnitude > 0 && ...
    abs(record.wheel.directionSign) == 1 && ...
    isfinite(record.wheel.efficiency) && ...
    record.wheel.efficiency > 0 && record.wheel.efficiency <= 1;
result.ready = result.metadataComplete && result.jointPass && ...
    result.imuPass && result.wheelPass;

blockers = strings(0, 1);
if ~result.metadataComplete, blockers(end + 1) = "标定元数据不完整"; end
if ~result.jointPass, blockers(end + 1) = "DM8009方向/零位/回零误差未通过"; end
if ~result.imuPass, blockers(end + 1) = "IMU符号或静止角速度RMS未通过"; end
if ~result.wheelPass, blockers(end + 1) = "轮侧方向/减速比/效率未通过"; end
result.blockers = blockers;
end
