function result = run_actuator_contract_check()
%RUN_ACTUATOR_CONTRACT_CHECK Print resolved limits and unresolved mappings.

actuators = serial_leg_actuator_parameters();
fprintf('关节电机: %s, 输出侧额定/峰值转矩: %.1f / %.1f N*m\n', ...
    actuators.jointMotor.model, ...
    actuators.jointMotor.ratedOutputTorqueNm, ...
    actuators.jointMotor.peakOutputTorqueNm);
fprintf('关节链轮: 20T -> 20T, 传动比幅值1:1, 符号/零位待标定\n');
fprintf('轮电机: %s + %s, 连续/堵转转矩: %.1f / %.1f N*m\n', ...
    actuators.wheelMotor.model, actuators.wheelMotor.controller, ...
    actuators.wheelMotor.ratedOutputTorqueNm, ...
    actuators.wheelMotor.stallOutputTorqueNm);
fprintf('六维暂用轮边拓扑: %s\n', ...
    actuators.wheelTransmission.selectedTopology);
fprintf('两级减速总幅值: %.3f:1, 轮端额定转速: %.2f rpm\n', ...
    actuators.wheelTransmission.cascadedRatioMagnitudeCandidate, ...
    actuators.wheelTransmission.ratedWheelSpeedRpmCandidate);
fprintf('轮端理想连续转矩: %.2f N*m（尚未乘效率）\n', ...
    actuators.wheelTransmission.continuousWheelTorqueIdealNmCandidate);
fprintf('注意: 该拓扑是暂定工程假设；效率、整机正方向和零位仍未标定。\n');

result = actuators;
end
